CREATE TABLE IF NOT EXISTS json_store (
    id TEXT PRIMARY KEY,
    data JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE json_store DISABLE ROW LEVEL SECURITY;
